# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-signing-variables

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0.6testResultsFiles'
    jdkArchitectureOption: 'x64'
    tasks: 'clean bundleRelease'

#- task: AndroidSigning@3
#  inputs:
#    apkFiles: '**/*.aab'
#    apksign: true
#    apksignerKeystoreFile: '$(key.name)'
#    apksignerKeystorePassword: '$(key.password)'
#    apksignerKeystoreAlias: '$(key.alias)'
#    apksignerKeyPassword: '$(keystore.password)'
#    zipalign: false

- task: DownloadSecureFile@1
  name: DownloadKeystore
  displayName: 'Download Keystore'
  inputs:
    secureFile: 'cats_key.jks'

- script: |
    echo "Removing existing signatures from the Android App Bundle..."
    zip -d app/build/outputs/bundle/release/app-release.aab 'META-INF/*'
  displayName: 'Remove existing signatures'

- script: |
    echo "Signing Android App Bundle with jarsigner..."
    echo "Keystore file path: $(DownloadKeystore.secureFilePath)"
    echo "Keystore password: $KEYSTORE_PASS"  # Be cautious when printing sensitive information
    echo "Key password: $KEY_PASS"  # Be cautious when printing sensitive information
    echo "Alias: $ALIAS"  # Be cautious when printing sensitive information
    echo "Current directory contents:"
    ls -la  # List files in the current directory
    jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
    -keystore "$(DownloadKeystore.secureFilePath)" \
    -storepass "$KEYSTORE_PASS" \
    -keypass "$KEY_PASS" \
    -tsa http://timestamp.digicert.com \
    -signedjar app/build/outputs/bundle/release/app-release-signed.aab \
    app/build/outputs/bundle/release/app-release.aab "$ALIAS"
  displayName: 'Sign Android App Bundle with jarsigner'
  env:
    KEYSTORE_PASS: $(key.password)
    KEY_PASS: $(keystore.password)
    ALIAS: $(key.alias)

- task: CopyFiles@2
  inputs:
    SourceFolder: 'app/build/outputs/bundle/release/'
    apkFiles: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- script: ls -R $(build.artifactStagingDirectory)
  displayName: 'List files in artifact staging directory'

- task: GooglePlayRelease@4
  inputs:
    serviceConnection: 'catsdevops'
    applicationId: 'com.fausto.cats'
    action: 'SingleBundle'
    bundleFile: 'app/build/outputs/bundle/release/app-release-signed.aab'
    apkFile: '**/*.aab'
    track: 'internal'