# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-signing-variables

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0.6testResultsFiles'
    jdkArchitectureOption: 'x64'
    testRunTitle: true
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksign: true
    apksignerKeystoreFile: '$(key.name)'
    apksignerKeystorePassword: '$(key.password)'
    apksignerKeystoreAlias: '$(key.alias)'
    apksignerKeyPassword: '$(keystore.password)'
    zipalign: false

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: GooglePlayRelease@4
  inputs:
    serviceConnection: 'catsdevops'
    applicationId: 'com.fausto.cats'
    action: 'SingleBundle'
    bundleFile: '$(build.artifactStagingDirectory)/**/*.apk'
    track: 'alpha'