# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  - group: android-signing-variables

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0.6testResultsFiles'
    jdkArchitectureOption: 'x64'
    tasks: 'clean bundleRelease'

#- task: AndroidSigning@3
#  inputs:
#    apkFiles: '**/*.aab'
#    apksign: true
#    apksignerKeystoreFile: '$(key.name)'
#    apksignerKeystorePassword: '$(key.password)'
#    apksignerKeystoreAlias: '$(key.alias)'
#    apksignerKeyPassword: '$(keystore.password)'
#    zipalign: false

- script: |
    jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore "$KEYSTORE_FILE" -storepass "$KEYSTORE_PASS" -keypass "$KEY_PASS" app-release.aab "$ALIAS"
  displayName: 'Sign Android App Bundle with jarsigner'
  env:
    KEYSTORE_FILE: $(key.name)
    KEYSTORE_PASS: $(key.password)
    KEY_PASS: $(keystore.password)
    ALIAS: $(key.alias)

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    apkFiles: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- script: ls -R $(build.artifactStagingDirectory)
  displayName: 'List files in artifact staging directory'

- task: GooglePlayRelease@4
  inputs:
    serviceConnection: 'catsdevops'
    applicationId: 'com.fausto.cats'
    action: 'SingleBundle'
    bundleFile: '**/*.aab'
    apkFile: '**/*.aab'
    track: 'internal'